This
is
the
current
front
end
of
the
website, it
is
pretty
basic.I
need
your
help
to
improve
the
front
end
of
this
site
dramatically, I
'm talking aesthetics, color, design, dynamics, loading speed, use of non deprecated packages, everything you can think off. I want this site to look really really good. Show me your best work ever.

src
-app

globals.css

@
import "tailwindcss"

/* :root {
  --background: #ffffff;
  --foreground: #171717;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
} */

layout.tsx

import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Ecocern Hub",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  )
}

page.tsx

import Header from "@/components/Header"
import HeroSection from "@/components/HeroSection"
import ServicesSection from "@/components/ServicesSection"
import ContactSection from "@/components/ContactSection"
import Footer from "@/components/Footer"

export default function Home() {
  return (
    // <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
    //   <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
    //     <Image
    //       className="dark:invert"
    //       src="/next.svg"
    //       alt="Next.js logo"
    //       width={180}
    //       height={38}
    //       priority
    //     />
    //     <ol className="font-mono list-inside list-decimal text-sm/6 text-center sm:text-left">
    //       <li className="mb-2 tracking-[-.01em]">
    //         Get started by editing{" "}
    //         <code className="bg-black/[.05] dark:bg-white/[.06] font-mono font-semibold px-1 py-0.5 rounded">
    //           src/app/page.tsx
    //         </code>
    //         .
    //       </li>
    //       <li className="tracking-[-.01em]">
    //         Save and see your changes instantly.
    //       </li>
    //     </ol>

    //     <div className="flex gap-4 items-center flex-col sm:flex-row">
    //       <a
    //         className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:w-auto"
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <Image
    //           className="dark:invert"
    //           src="/vercel.svg"
    //           alt="Vercel logomark"
    //           width={20}
    //           height={20}
    //         />
    //         Deploy now
    //       </a>
    //       <a
    //         className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 w-full sm:w-auto md:w-[158px]"
    //         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         Read our docs
    //       </a>
    //     </div>
    //   </main>
    //   <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
    //     <a
    //       className="flex items-center gap-2 hover:underline hover:underline-offset-4"
    //       href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <Image
    //         aria-hidden
    //         src="/file.svg"
    //         alt="File icon"
    //         width={16}
    //         height={16}
    //       />
    //       Learn
    //     </a>
    //     <a
    //       className="flex items-center gap-2 hover:underline hover:underline-offset-4"
    //       href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <Image
    //         aria-hidden
    //         src="/window.svg"
    //         alt="Window icon"
    //         width={16}
    //         height={16}
    //       />
    //       Examples
    //     </a>
    //     <a
    //       className="flex items-center gap-2 hover:underline hover:underline-offset-4"
    //       href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <Image
    //         aria-hidden
    //         src="/globe.svg"
    //         alt="Globe icon"
    //         width={16}
    //         height={16}
    //       />
    //       Go to nextjs.org →
    //     </a>
    //   </footer>
    // </div>
    <>
      <Header />
      <HeroSection />
      <ServicesSection />
      <ContactSection />
      <Footer />
    </>
  );
}

--components

ContactSection.tsx

import { MapPin, Phone, Mail, Clock, Send } from "lucide-react"

const ContactSection = () => {
  return (
    <section id="contact" className="py-24 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Get In Touch</h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Ready to start your environmental project? Contact our expert team for consultation and innovative solutions
            tailored to your needs.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Contact Information */}
          <div className="space-y-8">
            <div>
              <h3 className="text-2xl font-semibold text-gray-900 mb-6">Contact Information</h3>
              <div className="space-y-6">
                <div className="flex items-start space-x-4">
                  <div className="bg-green-50 p-3 rounded-lg">
                    <MapPin className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">Headquarters</h4>
                    <p className="text-gray-600">
                      Nairobi, Kenya
                      <br />
                      P.O. Box 12345-00100
                      <br />
                      Westlands, Nairobi
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-green-50 p-3 rounded-lg">
                    <Phone className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">Phone</h4>
                    <p className="text-gray-600">
                      +254 726 342 189
                      <br />
                      +254 726 342 189
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-green-50 p-3 rounded-lg">
                    <Mail className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">Email</h4>
                    <p className="text-gray-600">
                      info@ecocernhubconsultancy.co.ke
                      <br />
                      projects@ecocernhubconsultancy.co.ke
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-green-50 p-3 rounded-lg">
                    <Clock className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">Business Hours</h4>
                    <p className="text-gray-600">
                      Monday - Friday: 8:00 AM - 6:00 PM
                      <br />
                      Saturday: 9:00 AM - 2:00 PM
                      <br />
                      Sunday: Closed
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Service Areas */}
            <div className="bg-gradient-to-br from-white to-gray-50 rounded-xl border border-gray-200 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Service Areas</h3>
              <div className="grid grid-cols-2 gap-4 text-sm text-gray-600">
                <div>
                  <h5 className="font-semibold text-gray-900 mb-2">East Africa</h5>
                  <ul className="space-y-1">
                    <li>• Kenya</li>
                    <li>• Tanzania</li>
                    <li>• Uganda</li>
                    <li>• Rwanda</li>
                  </ul>
                </div>
                <div>
                  <h5 className="font-semibold text-gray-900 mb-2">International</h5>
                  <ul className="space-y-1">
                    <li>• Sub-Saharan Africa</li>
                    <li>• Americas</li>
                    <li>• Asia Pacific</li>
                    <li>• Europe</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          {/* Contact Form */}
          <div>
            <div className="bg-white shadow-lg border border-gray-200 rounded-xl p-6">
              <h3 className="text-xl font-semibold text-gray-900 mb-6">Send us a Message</h3>
              <form className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-gray-900 block mb-2">First Name</label>
                    <input
                      type="text"
                      placeholder="John"
                      className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-900 block mb-2">Last Name</label>
                    <input
                      type="text"
                      placeholder="Doe"
                      className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-sm font-medium text-gray-900 block mb-2">Email</label>
                  <input
                    type="email"
                    placeholder="john.doe@example.com"
                    className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="text-sm font-medium text-gray-900 block mb-2">Phone</label>
                  <input
                    type="tel"
                    placeholder="+254 123 456 789"
                    className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="text-sm font-medium text-gray-900 block mb-2">Service Required</label>
                  <input
                    type="text"
                    placeholder="Environmental Impact Assessment"
                    className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>

                <div>
                  <label className="text-sm font-medium text-gray-900 block mb-2">Message</label>
                  <textarea
                    placeholder="Tell us about your project requirements..."
                    rows={4}
                    className="w-full px-3 py-2 border border-gray-300 bg-white text-gray-900 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent resize-vertical"
                  />
                </div>

                <button className="w-full bg-gradient-to-r from-green-600 to-green-500 text-white px-6 py-3 rounded-lg hover:shadow-lg transition-all duration-300 font-semibold flex items-center justify-center gap-2">
                  <Send className="h-4 w-4" />
                  Send Message
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default ContactSection;

Footer.tsx

import { Mail, Phone, MapPin, Linkedin, Twitter, Facebook, ArrowRight } from "lucide-react"
import Image from "next/image"

const Footer = () => {
  return (
    <footer className="bg-green-700 text-white">
      <div className="container mx-auto px-4 py-16">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {/* Company Info */}
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <Image className="h-8 w-8 text-green-600" src="/ecocern.svg" alt="logo" width={16} height={16} priority />
              <span className="text-xl font-bold">Ecocern Hub Consultancy</span>
            </div>
            <p className="text-white/80 text-sm">
              Leading environmental consultancy and supplies provider offering scientific and cutting-edge technical
              solutions in Kenya, Africa, and worldwide.
            </p>
            <div className="flex space-x-4">
              <button className="bg-white/10 hover:bg-white/20 p-2 rounded-lg transition-colors">
                <Linkedin size={20} />
              </button>
              <button className="bg-white/10 hover:bg-white/20 p-2 rounded-lg transition-colors">
                <Twitter size={20} />
              </button>
              <button className="bg-white/10 hover:bg-white/20 p-2 rounded-lg transition-colors">
                <Facebook size={20} />
              </button>
            </div>
          </div>

          {/* Environmental Services */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Environmental Services</h3>
            <ul className="space-y-2 text-sm text-white/80">
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Environmental Impact Assessment
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Regulatory Approvals
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Environmental Planning
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Industrial Services
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Water & Hydrogeology
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Social Impact Assessment
                </a>
              </li>
            </ul>
          </div>

          {/* General Supplies */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">General Supplies</h3>
            <ul className="space-y-2 text-sm text-white/80">
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Industrial Supplies
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Construction Materials
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Maintenance Tools
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Logistics Solutions
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Electrical Supplies
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-white transition-colors">
                  Safety Equipment
                </a>
              </li>
            </ul>
          </div>

          {/* Newsletter */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">Stay Updated</h3>
            <p className="text-sm text-white/80">
              Subscribe to our newsletter for the latest environmental insights and supplies updates.
            </p>
            <div className="space-y-2">
              <input
                type="email"
                placeholder="Enter your email"
                className="w-full px-3 py-2 bg-white/10 border border-white/20 text-white placeholder:text-white/60 rounded-lg focus:outline-none focus:ring-2 focus:ring-white/30"
              />
              <button className="bg-white text-green-600 px-4 py-2 rounded-lg hover:bg-gray-100 transition-colors flex items-center gap-2 font-medium">
                Subscribe
                <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </div>

        {/* Contact Information */}
        <div className="border-t border-white/20 mt-12 pt-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-sm">
            <div className="flex items-center space-x-2">
              <MapPin size={16} />
              <span>Nairobi, Kenya | P.O. Box 12345-00100</span>
            </div>
            <div className="flex items-center space-x-2">
              <Phone size={16} />
              <span>+254 726 342 189</span>
            </div>
            <div className="flex items-center space-x-2">
              <Mail size={16} />
              <span>info@ecocernhubconsultancy.co.ke</span>
            </div>
          </div>
        </div>

        {/* Copyright */}
        <div className="border-t border-white/20 mt-8 pt-6 text-center">
          <p className="text-sm text-white/80">
            © 2025 Ecocern Hub Ltd. All rights reserved. |<span className="mx-1">Privacy Policy</span> |
            <span className="mx-1">Terms of Service</span>
          </p>
        </div>
      </div>
    </footer>
  )
}

export default Footer;

Header.tsx
;("use client")

import type React from "react"

import { Menu, Phone, X } from "lucide-react"
import Image from "next/image"
import { useState, useEffect } from "react"

const Header = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  const handleWhatsAppClick = () => {
    window.open("https://wa.me/254726342189", "_blank")
  }

  const handlePhoneClick = () => {
    window.location.href = "tel:+254726342189"
  }

  const navItems = [
    { name: "Home", href: "#home" },
    { name: "Services", href: "#services" },
    { name: "About", href: "#about" },
    { name: "Projects", href: "#projects" },
    { name: "News & Insights", href: "#news&insights" },
    { name: "Contact", href: "#contact" },
  ]

  return (
    <header
      className={`bg-white/95 backdrop-blur-sm border-b border-gray-200 sticky top-0 z-50 transition-all duration-300 ${
        isScrolled ? "shadow-sm" : ""
      }`}
    >
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex items-center space-x-2">
            <Image className="h-8 w-8 text-green-600" src="/ecocern.svg" alt="Icon logo" width={16} height={16} />
            <span className="text-xl font-bold text-gray-900">Ecocern Hub</span>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            {navItems.map((item) => (
              <a
                key={item.name}
                href={item.href}
                className="text-gray-700 hover:text-green-600 transition-colors font-medium"
              >
                {item.name}
              </a>
            ))}
          </nav>

          {/* Contact Info & CTA - Desktop */}
          <div className="hidden lg:flex items-center space-x-4">
            <div className="flex items-center space-x-2 text-sm text-gray-600">
              <Phone size={16} />
              <span>+254 726 342 189</span>
            </div>
            <button
              onClick={handleWhatsAppClick}
              className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition-colors text-sm font-medium"
            >
              Get Consultation
            </button>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="md:hidden p-2 rounded-lg hover:bg-gray-100 transition-colors"
            aria-label="Toggle navigation"
          >
            {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>

        {/* Mobile Navigation */}
        {isMobileMenuOpen && (
          <div className="md:hidden bg-white shadow-lg rounded-lg mt-2 mb-4">
            {/* Mobile Menu Items */}
            <div className="flex flex-col p-2 space-y-1">
              {navItems.map((item) => (
                <a
                  key={item.name}
                  href={item.href}
                  onClick={() => setIsMobileMenuOpen(false)}
                  className="px-4 py-3 text-gray-700 hover:bg-green-50 hover:text-green-600 rounded-lg transition-colors font-medium"
                >
                  {item.name}
                </a>
              ))}
            </div>

            {/* Mobile Contact Info */}
            <div className="border-t border-gray-100 p-4">
              <div onClick={handlePhoneClick} className="flex items-center space-x-3 text-gray-700 mb-4">
                <Phone size={18} className="text-green-600" />
                <span>+254 726 342 189</span>
              </div>
              <button
                onClick={handleWhatsAppClick}
                className="w-full bg-green-600 text-white px-4 py-3 rounded-lg hover:bg-green-700 transition-colors font-medium"
              >
                Get Consultation
              </button>
            </div>
          </div>
        )}
      </div>
    </header>
  )
}

export default Header;

HeroSection.tsx

import { ArrowRight, Shield, Globe, Award } from "lucide-react"
import Image from "next/image"

const HeroSection = () => {
  return (
    <section id="home" className="relative min-h-screen flex items-center">
      {/* Background Image */}
      <div className="absolute inset-0 z-0">
        <Image
          className="w-full h-full object-cover"
          src="/hero-environmental.jpg"
          alt="Environmental consulting services"
          width={180}
          height={38}
          priority
        />
        <div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/70 to-white/30"></div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-4 relative z-10">
        <div className="max-w-3xl">
          <div className="flex items-center space-x-2 mb-6">
            <Shield className="h-6 w-6 text-green-600" />
            <span className="text-green-600 font-semibold">Environmental Services & General Supplies</span>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
            Your Partner for
            <span className="text-green-600"> Environmental Solutions </span>& Quality Supplies
          </h1>

          <p className="text-lg md:text-xl text-gray-600 mb-8 leading-relaxed">
            Ecocern Hub provides comprehensive environmental services and high-quality general supplies to meet all your
            business needs. From environmental impact assessments to industrial supplies, we deliver excellence across
            Kenya and beyond.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 mb-12">
            <button className="bg-gradient-to-r from-green-600 to-green-500 text-white px-8 py-3 rounded-lg hover:shadow-lg hover:scale-105 transition-all duration-300 font-semibold flex items-center justify-center gap-2 group">
              Get Started Today
              <ArrowRight className="group-hover:translate-x-1 transition-transform" />
            </button>
            <button className="border-2 border-green-600 text-green-600 px-8 py-3 rounded-lg hover:bg-green-600 hover:text-white transition-colors font-medium">
              Our Services
            </button>
          </div>

          {/* Key Features */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="flex items-center space-x-3">
              <div className="bg-green-50 p-2 rounded-lg">
                <Globe className="h-5 w-5 text-green-600" />
              </div>
              <div>
                <p className="font-semibold text-gray-900">International Reach</p>
                <p className="text-sm text-gray-600">Kenya, Africa & Worldwide</p>
              </div>
            </div>
            <div className="flex items-center space-x-3">
              <div className="bg-green-50 p-2 rounded-lg">
                <Award className="h-5 w-5 text-green-600" />
              </div>
              <div>
                <p className="font-semibold text-gray-900">Expert Solutions</p>
                <p className="text-sm text-gray-600">Cutting-edge capabilities</p>
              </div>
            </div>
            <div className="flex items-center space-x-3">
              <div className="bg-green-50 p-2 rounded-lg">
                <Shield className="h-5 w-5 text-green-600" />
              </div>
              <div>
                <p className="font-semibold text-gray-900">Regulatory Compliance</p>
                <p className="text-sm text-gray-600">Smart collaborative solutions</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default HeroSection;

ServicesSection.tsx

import {
  FileText,
  Shield,
  TreePine,
  Factory,
  Waves,
  Users,
  Package,
  Wrench,
  Truck,
  Building,
  Zap,
  CheckCircle,
} from "lucide-react"

const ServicesSection = () => {
  const environmentalServices = [
    {
      icon: FileText,
      title: "Environmental Impact Assessment (EIA)",
      description:
        "Comprehensive environmental assessments identifying potential impacts on air quality, water resources, biodiversity, and socio-economic factors.",
      features: [
        "Thorough impact analysis",
        "Regulatory compliance reports",
        "Mitigation measures",
        "Project alternatives evaluation",
      ],
    },
    {
      icon: Shield,
      title: "Regulatory Approvals & Permitting",
      description:
        "Expert guidance through complex regulatory frameworks ensuring compliance with federal, provincial, and municipal requirements.",
      features: [
        "Strategic approval processes",
        "Stakeholder collaboration",
        "Permit acquisition",
        "Compliance management",
      ],
    },
    {
      icon: TreePine,
      title: "Environmental Planning",
      description:
        "Sustainable development planning that balances economic growth with environmental protection and community needs.",
      features: [
        "Sustainable development",
        "Environmental management plans",
        "Monitoring programs",
        "Long-term compliance",
      ],
    },
    {
      icon: Factory,
      title: "Industrial Environmental Services",
      description:
        "Specialized services for industrial facilities including air quality assessments, waste management, and workplace safety.",
      features: ["Air quality monitoring", "Waste management", "Safety protocols", "Environmental audits"],
    },
    {
      icon: Waves,
      title: "Water & Hydrogeology",
      description: "Water resource management, hydrogeological assessments, and aquatic ecosystem protection services.",
      features: ["Water quality testing", "Hydrogeological studies", "Aquatic assessments", "Resource management"],
    },
    {
      icon: Users,
      title: "Social Impact Assessment",
      description:
        "Comprehensive evaluation of project impacts on communities including socio-economic and cultural considerations.",
      features: ["Community engagement", "Cultural assessments", "Socio-economic analysis", "Stakeholder consultation"],
    },
  ]

  const supplyServices = [
    {
      icon: Package,
      title: "Industrial Supplies",
      description: "High-quality industrial equipment, tools, and materials for various industries and applications.",
      features: ["Quality equipment", "Reliable suppliers", "Bulk ordering", "Technical support"],
    },
    {
      icon: Building,
      title: "Construction Materials",
      description: "Complete range of construction materials from foundation to finishing for all your building needs.",
      features: ["Building materials", "Quality assurance", "Competitive pricing", "Timely delivery"],
    },
    {
      icon: Wrench,
      title: "Maintenance Tools",
      description: "Comprehensive range of tools and equipment for facility maintenance and repairs.",
      features: ["Hand tools", "Power tools", "Safety equipment", "Consumables"],
    },
    {
      icon: Truck,
      title: "Logistics Solutions",
      description: "Efficient supply chain and logistics services to ensure timely delivery of your materials.",
      features: ["Transportation", "Warehousing", "Inventory management", "Nationwide coverage"],
    },
    {
      icon: Zap,
      title: "Electrical Supplies",
      description: "Complete electrical components and systems for commercial and industrial applications.",
      features: ["Wiring", "Lighting", "Control systems", "Safety equipment"],
    },
    {
      icon: Shield,
      title: "Safety Equipment",
      description: "Personal protective equipment and safety gear to ensure workplace safety compliance.",
      features: ["Protective clothing", "Safety signage", "First aid", "Emergency equipment"],
    },
  ]

  return (
    <section id="services" className="py-24 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Our Services</h2>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            We offer comprehensive environmental consulting services and quality general supplies with expertise across
            multiple disciplines to meet your precise needs.
          </p>
        </div>

        {/* Environmental Services Section */}
        <div className="mb-16">
          <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">Environmental Services</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {environmentalServices.map((service, index) => (
              <div
                key={index}
                className="bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 p-6"
              >
                <div className="bg-green-50 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                  <service.icon className="h-6 w-6 text-green-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{service.title}</h3>
                <p className="text-gray-600 mb-4">{service.description}</p>
                <ul className="space-y-2 mb-6">
                  {service.features.map((feature, featureIndex) => (
                    <li key={featureIndex} className="flex items-center space-x-2 text-sm">
                      <CheckCircle className="h-4 w-4 text-green-600 flex-shrink-0" />
                      <span className="text-gray-600">{feature}</span>
                    </li>
                  ))}
                </ul>
                <button className="w-full border border-green-600 text-green-600 px-4 py-2 rounded-lg hover:bg-green-600 hover:text-white transition-colors">
                  Learn More
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* General Supplies Section */}
        <div className="mb-16">
          <h3 className="text-2xl font-bold text-gray-900 mb-8 text-center">General Supplies</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {supplyServices.map((service, index) => (
              <div
                key={index}
                className="bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100 p-6"
              >
                <div className="bg-green-50 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                  <service.icon className="h-6 w-6 text-green-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{service.title}</h3>
                <p className="text-gray-600 mb-4">{service.description}</p>
                <ul className="space-y-2 mb-6">
                  {service.features.map((feature, featureIndex) => (
                    <li key={featureIndex} className="flex items-center space-x-2 text-sm">
                      <CheckCircle className="h-4 w-4 text-green-600 flex-shrink-0" />
                      <span className="text-gray-600">{feature}</span>
                    </li>
                  ))}
                </ul>
                <button className="w-full border border-green-600 text-green-600 px-4 py-2 rounded-lg hover:bg-green-600 hover:text-white transition-colors">
                  Learn More
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center mt-16">
          <button className="bg-gradient-to-r from-green-600 to-green-500 text-white px-8 py-3 rounded-lg hover:shadow-lg hover:scale-105 transition-all duration-300 font-semibold">
            Discuss Your Requirements
          </button>
        </div>
      </div>
    </section>
  )
}

export default ServicesSection;

package.json

{
  ;("name")
  : "ecocern-hub",
\
  "version": "0.1.0",
  "private": true,
  "scripts":
  ;("dev")
  : \"next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  ,
  \"dependencies\": {
    "lucide-react": "^0.539.0",
    "next": "15.4.6",
    "react": "19.1.0",
    "react-dom": "19.1.0"
}
,
  \"devDependencies":
{
  ;("@tailwindcss/postcss")
  : "^4",
    \"@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4",
    "typescript": "^5"
}
}
\
